#!/bin/sh
###############################
# backup user data
# (c) 2009 by Niels Dettenbach
# <nd@syndicat.com> GPL

# config
XENBACK_CONF="/etc/xenbackup.conf"
# read the config
. $XENBACK_CONF


echo "From: $EMAIL_FROM" > $LOGFILE
echo "Subject: SNAPBACKUP on Host $HOSTN at $DOMAINN" >> $LOGFILE
echo "" >> $LOGFILE
echo "" >> $LOGFILE
date  >>  $LOGFILE
echo "" >> $LOGFILE

#echo "Backup Dom0" >> $LOGFILE
#/usr/sbin/backup-manager -v -c /etc/backup-manager-dom0.conf >> $LOGFILE
#echo ""

echo "Backup Guests:" >> $LOGFILE
echo ""
# mount and backup
$SNAPBACKUPALLGUEST >> $LOGFILE

$BIN_CAT $LOGFILE | $BIN_SENDMAIL $EMAIL_TO
