#!/bin/sh
########################################
## DO Snapbacks one by one
## XEN DOMU LVM backup script
## by Niels <nd@syndicat.com>
## https://www.syndicat.com/
## (c) 2015-2020 (GPLv2)
## v1.0a
########################################



XENBACK_CONF="/etc/xenbackup.conf"
# read the config
source $XENBACK_CONF


echo ""
echo "Mount BACKUP Device:"
echo "===================="
echo " "
$BIN_MOUNT -t $BCKDEV_FS $BCKDEV $BCKMNTP && echo "done. " || echo "could NOT mount Backup Device (or still mounted) !" 
echo " "
echo "space:"
$BIN_DF -h $BCKMNTP

# debug
#exit

echo " "
echo "DO XEN SNAPBACKS"
echo "================"
echo " "

while read NAME
do
	# init
        BM_TARBALL_DIRECTORIES=""
	export BM_TARBALL_DIRECTORIES
	TARBALL_DIRECTORY=""
	export TARBALL_DIRECTORY

	BDOM=$($BIN_ECHO $NAME | $BIN_CUT -d '|' -f 1)
	BNAME=$($BIN_ECHO $NAME | $BIN_CUT -d '|' -f 2)
	BVOL=$($BIN_ECHO $NAME | $BIN_CUT -d '|' -f 3)
	BFSTYPE=$($BIN_ECHO $NAME | $BIN_CUT -d '|' -f 4)
	BFOPTS=$($BIN_ECHO $NAME | $BIN_CUT -d '|' -f 5)


	if [ -n "$BFOPTS" ]; then
		echo "DOMAIN:	$BNAME"
		echo "DOMPATH:	$BDOM"
		echo "MOUNT:	$BVOL"
		echo "AS:	$BFSTYPE"
		echo "WITH:	$BFOPTS"
		echo "________________________"

		#BDOM=$1
		#BNAME=$2
		#SRCVOL=$3
		#BFSTYPE=$4
		#BFOPTS=$5

		$SNAPBACKUPMNT $BDOM $BNAME $BVOL $BFSTYPE $BFOPTS && echo "Domain mounted" || echo "Domain mount ERROR!"

		TARBALL_DIRECTORY=$MNTSOURCEDIR/$BDOM/$BNAME
		echo " ";
		echo "Directory in Backup aufnehmen: $TARBALL_DIRECTORY" 


		# set dirs to backup as var for backup-manager
		BM_TARBALL_DIRECTORIES="$BM_TARBALL_DIRECTORIES $TARBALL_DIRECTORY"
		export BM_TARBALL_DIRECTORIES

		# example
		#BM_TARBALL_DIRECTORIES="/4backup/netbsd2/root/ /4backup/gentoo/root/"

		export BM_TARBALL_DIRECTORIES

		echo " "
		echo "sichere Directories: $BM_TARBALL_DIRECTORIES"
		echo " "
		$BIN_DATE
		echo " "
		echo "starte BACKUP-MANAGER:"
		$BIN_BACKUPMAN -v -c $BM_CONFIGFILE
		echo " "
		echo "beende BACKUP-MANAGER:"
		echo " "

		$SNAPBACKUPUMNT $BDOM $BNAME $BVOL $BFSTYPE $BFOPTS && echo "Domain unmounted" || echo "Domain umount ERROR!"
                echo " ";
		$BIN_DATE
		echo " "

        fi
done <  $SBCONFIGFILE


echo ""
echo "UNmount BACKUP Device:"
echo "===================="
echo " "
$BIN_UMOUNT $BCKMNTP && echo "done. " || echo "could NOT unmount Backup Device (possibly still mounted) !"
