#!/bin/sh
########################################
## UNMOUNT / CLOSE ALL Snapbacks 
##
## by Niels
## https://www.syndicat.com/
## (c) 2015 (GPLv2)
########################################

# config
XENBACK_CONF="/etc/xenbackup.conf"
# read the config
. $XENBACK_CONF

echo ""
echo "Unmount BACKUP Device:"
echo "================"
echo " "
$BIN_DATE
echo " "
$BIN_UMOUNT $BCKMNTP && echo "done. " || echo "could NOT unmount Backup Device !" 


echo " "
echo "DO UMOUNT XEN SNAPBACKS"
echo "================"
echo " "

while read NAME
do
        BDOM=$($BIN_ECHO $NAME | $BIN_CUT -d '|' -f 1)
        BNAME=$($BIN_ECHO $NAME | $BIN_CUT -d '|' -f 2)
        BVOL=$($BIN_ECHO $NAME | $BIN_CUT -d '|' -f 3)


        if [ -n "$BVOL" ]; then
                echo "DOMAIN:   $BNAME"
                echo "DOMPATH:  $BDOM"
                echo "MOUNT:    $BVOL"
                echo "________________________"

		$SNAPBACKUPUMNT $BDOM $BNAME $BVOL && echo "Domain unmounted" || echo "Domain umount ERROR!"
		echo " ";

	fi
done <  $SBCONFIGFILE

echo " "
$BIN_DATE
echo " "

