#!/bin/bash
#####################################
## Snaphot Backup
##
## usage:
## snaps_backup <volume> <fstype> <mount string>

#####################################
## config

# temp snapshot mount dir 
MNTSOURCEDIR="/4backup"

# backup target dir (mountpoint of backup device)
TARGETDIR="/backup/guests"

# target path (by VM name / Xen DomU name here)
TARGETPATH="/backup/guests/$BDOM"

# snapshot capacity
SNAPSIZE="10G"

#####################################

# parameters
BDOM=$1
BNAME=$2
SRCVOL=$3
BFSTYPE=$4
BFOPTS=$5

MNTSOURCEPRE=$MNTSOURCEDIR/$BDOM
MNTSOURCEPATH=$MNTSOURCEPRE/$BNAME
TARGETPRE=$TARGETDIR/$BDOM
TARGETPATH=$TARGETPRE/$BNAME
# backup volume
SNAPVOLUME=$SRCVOL.back

TARBALL_DIRECTORIES=""
export TARBALL_DIRECTORIES

## MAIN

# create snapshot
/sbin/lvcreate -L$SNAPSIZE -s -n $SNAPVOLUME $SRCVOL

# create Backup-DIR
if [ -d "$MNTSOURCEPATH" ]
then 
	echo "Backup-Directory $MNTSOURCEPATH FOUND"
else
	/bin/mkdir -p $MNTSOURCEPATH && echo "Backup-Directory $MNTSOURCEPATH CREATED" || echo "Backup-Directory $MNTSOURCEPATH NOT CREATED!"
fi

/bin/mount -t $BFSTYPE -o$BFOPTS $SNAPVOLUME $MNTSOURCEPATH

# for backup manager
#echo "altes DIR: $BM_TARBALL_DIRECTORIES"
TARBALL_DIRECTORIES="$MNTSOURCEPATH"
#export TARBALL_DIRECTORIES
#echo "Erfasse DIR: $TARBALL_DIRECTORIES"


#debug
#/bin/ls -al  $MNTSOURCEPATH
