#!/bin/sh
#####################################
## Snaphot Backup
##
## by Niels Dettenbach <nd@syndicat.com>

usage="usage: $0 <vm name> <vol name> <vol device> <fs type> <mount opts>"


# config
XENBACK_CONF="/etc/xenbackup.conf"
# read the config
source $XENBACK_CONF
#TARGETPATH="/backup/guests/$BDOM"


# parameters
BDOM=$1
BNAME=$2
SRCVOL=$3
BFSTYPE=$4
BFOPTS=$5

MNTSOURCEPRE=$MNTSOURCEDIR/$BDOM
MNTSOURCEPATH=$MNTSOURCEPRE/$BNAME
TARGETPRE=$TARGETDIR/$BDOM
TARGETPATH=$TARGETPRE/$BNAME
# backup volume
SNAPVOLUME=$SRCVOL.back

TARBALL_DIRECTORIES=""
export TARBALL_DIRECTORIES


### MAIN

if [ $5 ] && [ $BIN_LVCREATE ]
then


   # create snapshot
   $BIN_LVCREATE -L$SNAPSIZE -s -n $SNAPVOLUME $SRCVOL

   # create Backup-DIR
   if [ -d "$MNTSOURCEPATH" ]
      then
         $BIN_ECHO "Backup-Directory $MNTSOURCEPATH FOUND"
      else
         $BIN_MKDIR -p $MNTSOURCEPATH && $BIN_ECHO "Backup-Directory $MNTSOURCEPATH CREATED" || $BIN_ECHO "Backup-Directory $MNTSOURCEPATH NOT CREATED!"
   fi

   $BIN_MOUNT -t $BFSTYPE -o$BFOPTS $SNAPVOLUME $MNTSOURCEPATH

   # for backup manager
   #echo "old DIR: $BM_TARBALL_DIRECTORIES"
   TARBALL_DIRECTORIES="$MNTSOURCEPATH"
   #export TARBALL_DIRECTORIES
   #echo "catch DIR: $TARBALL_DIRECTORIES"


   #debug
   #$BIN_LS  $MNTSOURCEPATH

else
   echo $usage
fi
