#!/bin/bash
#####################################
## Snaphot Backup
##
## usage:
## snaps_backup <volume> <fstype> <mount string>

# config
XENBACK_CONF="/etc/xenbackup.conf"
# read the config
source $XENBACK_CONF
#TARGETPATH="/backup/guests/$BDOM"


# parameters
BDOM=$1
BNAME=$2
SRCVOL=$3
BFSTYPE=$4
BFOPTS=$5

MNTSOURCEPRE=$MNTSOURCEDIR/$BDOM
MNTSOURCEPATH=$MNTSOURCEPRE/$BNAME
TARGETPRE=$TARGETDIR/$BDOM
TARGETPATH=$TARGETPRE/$BNAME
# backup volume
SNAPVOLUME=$SRCVOL.back

TARBALL_DIRECTORIES=""
export TARBALL_DIRECTORIES

## MAIN

# create snapshot
$BIN_LVCREATE -L$SNAPSIZE -s -n $SNAPVOLUME $SRCVOL

# create Backup-DIR
if [ -d "$MNTSOURCEPATH" ]
then 
	$BIN_ECHO "Backup-Directory $MNTSOURCEPATH FOUND"
else
	$BIN_MKDIR -p $MNTSOURCEPATH && $BIN_ECHO "Backup-Directory $MNTSOURCEPATH CREATED" || $BIN_ECHO "Backup-Directory $MNTSOURCEPATH NOT CREATED!"
fi

$BIN_MOUNT -t $BFSTYPE -oro,$BFOPTS $SNAPVOLUME $MNTSOURCEPATH

# for backup manager
#echo "old DIR: $BM_TARBALL_DIRECTORIES"
TARBALL_DIRECTORIES="$MNTSOURCEPATH"
#export TARBALL_DIRECTORIES
#echo "catch DIR: $TARBALL_DIRECTORIES"


#debug
#$BIN_LS  $MNTSOURCEPATH
