#!/bin/sh
#####################################
## Snaphot Backup
##
##
## by Niels Dettenbach <nd@syndicat.com>

usage="usage: $0 <vm name> <vol name> <vol device>"

## usage:
## snaps_backup <volume> <fstype> <mount string>

# config
XENBACK_CONF="/etc/xenbackup.conf"
# read the config
. $XENBACK_CONF

# parameters
BDOM=$1
BNAME=$2
SRCVOL=$3
#BFSTYPE=$4
#BFOPTS=$5

MNTSOURCEPRE=$MNTSOURCEDIR/$BDOM
MNTSOURCEPATH=$MNTSOURCEPRE/$BNAME

# backup volume
SNAPVOLUME=$SRCVOL.back

## MAIN

if [ $3 ] && [ $BIN_LVREMOVE ] && [ $BIN_UMOUNT ]
then

   if [ -b $SNAPVOLUME ]
      then
      #debug
      #$BIN_LS -al  $MNTSOURCEPATH

      $BIN_UMOUNT -f $MNTSOURCEPATH && $BIN_ECHO "Unmounted $MNTSOURCEPATH" || $BIN_ECHO "could NOT unmount $MNTSOURCEPATH !"
      #sleep 1
      $BIN_LVREMOVE -f "$SNAPVOLUME" && $BIN_ECHO "Remove $SNAPVOLUME" || $BIN_ECHO "cloud NOT remove $SNAPVOLUME !"

   else
      $BIN_ECHO "Snapvolume $SNAPVOLUME NOT EXIST !"
   fi

else
   echo $usage

fi
